# Funciones de transformacion de coordenadas

Para encontrar las transformaciones de coordenadas, diseñamos pang y luego yo funciones de transformacion

In [1]:
import numpy as np

## Funciones de pang

In [2]:
from pang_functions import rot, trans

## Mis funciones

In [3]:
from my_functions import get_trans

## Puntos de ejemplo:

* C1: puntos base
* C2: C1 desplazado [0.5, 0.2]
* C3: C1 rotado 90 grados

In [4]:
C1 = np.array([
    [0,1],
    [1,1],
    [1,0],
    [0,0]
])
C2 = np.array([
    [0.5,1.2],
    [1.5,1.2],
    [1.5,0.2],
    [0.5,0.2]
])
C3 = C1@rot(90)


In [5]:
C3

array([[-1.000000e+00,  6.123234e-17],
       [-1.000000e+00,  1.000000e+00],
       [ 6.123234e-17,  1.000000e+00],
       [ 0.000000e+00,  0.000000e+00]])

In [6]:
C2_2 = np.array([[0.49,0.21]]) +.99*C1@rot(0.01)
C2_2

array([[0.48982721, 1.19999998],
       [1.4798272 , 1.20017277],
       [1.47999998, 0.21017279],
       [0.49      , 0.21      ]])

### Transformaciones entre los puntos de ejemplo con las funciones de pang

pruebo a calcular las transformaciones de los 4 puntos con las funciones de pang

In [7]:
trans(C1, C2)

(0.49999982689853045,
 0.20000015661946832,
 4.474357422748938e-06,
 1.0000000121424764)

In [8]:
trans(C1, C2_2)

(0.48999982732506014,
 0.2100001537130941,
 0.010004681442302238,
 0.9900000303760956)

In [9]:
trans(C1, C3)

(-5.253071776056878e-07,
 -2.1821786672631713e-06,
 90.0002170593302,
 1.0000004143534542)

In [10]:
trans(C2, C3)

(0.19999777060220467,
 -0.49999736897434177,
 90.00006046477937,
 0.999999483702028)

Dan valores aceptables, pero con diferencias decimales

### Transformaciones entre los puntos de ejemplo con mis funciones

Ahora pruebo a hallar las transformaciones con mis funciones

In [11]:
get_trans(C1, C2)

(array([0.5, 0.2]), 0.0, 1.0)

In [12]:
get_trans(C1, C2_2)

(array([0.49, 0.21]), 0.01000000000000394, 0.99)

In [13]:
get_trans(C1, C3)

(array([0., 0.]), 90.0, 1.0)

In [14]:
get_trans(C2, C3)

(array([ 0.2, -0.5]), 90.0, 1.0)

Dan los valores exactos, sin decimales

## Mas puntos de referencia, para probar las funciones con mas variacion

Uso las coordenadas de las casillas en distintas transformaciones: el sistema de referencia de pyPDF2, el de OpenCV de un examen escaneado y el de OpenCV de nuevo pero girado 90 grados

In [15]:
from example_boxes import boxes_pypdf, boxes_scan, boxes_scan90

### Con las funciones de pang

In [16]:
trans(boxes_pypdf, boxes_scan)

(1101.425542993863, 4477.201640347557, 0.26211627308819774, -5.331970072284408)

In [17]:
trans(boxes_scan, boxes_scan90)

(0.204136504872387, 3213.8805786800995, -90.0093047734473, 0.9998787554866239)

In [18]:
trans(boxes_pypdf, boxes_scan90)

(4476.672104425484, 2111.873408232511, 90.25303490178466, 5.331286896402964)

la transformación de pyPDF2 a la escaneada sin girar es extraña, en vez de invertir las coordenadas con el giro las invierte con la escala

### Con mis funciones

In [19]:
get_trans(boxes_pypdf, boxes_scan)

(array([1107.87317626, 4468.27709427]), -179.96980467172529, 5.314611082531149)

In [20]:
get_trans(boxes_scan, boxes_scan90)

(array([-2.61704650e-01,  3.21388533e+03]),
 -90.00706051964781,
 1.000061688956147)

In [21]:
get_trans(boxes_pypdf, boxes_scan90)

(array([4468.21125099, 2105.37823331]), 90.02315408130032, 5.315086476944962)

ambas funciones dan resultados similares, pero prefiero las mias por como tratan invertir el ángulo