# Comparacion de coordenadas de las casillas

In [ ]:
import numpy as np
import json

from my_functions import get_trans #, get_rotation # called by get_trans
from pyex_scan import find_qrs_v1

# Files used

Base directory

In [ ]:
base_dir = '../multiple_choice_example/'

Statement files, for default coordinates

In [ ]:
st_file1 = base_dir + 'question/question_11111.pdf'
st_file2 = base_dir + 'question/question_22222.pdf'
st_file3 = base_dir + 'question/question_33333.pdf'
st_file4 = base_dir + 'question/question_44444.pdf'

JSON files

In [ ]:
st_json_file1 = base_dir + 'json/question_11111.json'

filled_json_file3 = base_dir + 'json/scan_33333.json'

Solution files, for scanned coordinates

In [ ]:
# scanned exams 1 and 2
ex_file1 = base_dir + 'scanned/scanned_11111.pdf'
ex_file2 = base_dir + 'scanned/scanned_22222.pdf'

# scanned 2 rotated by 45º, 90º and 180º
ex_file2_rot45 = base_dir + 'scanned/scanned_22222_rot45.pdf'
ex_file2_rot90 = base_dir + 'scanned/scanned_22222_rot90.pdf'
ex_file2_rot180 = base_dir + 'scanned/scanned_22222_rot180.pdf'

# filled exams 3 and 4
ex_file3 = base_dir + 'filled/filled_33333.pdf'
ex_file4 = base_dir + 'filled/filled_44444.pdf'

# filled 3 rotated by 90º and 180º
ex_file3_rot90 = base_dir + 'filled/filled_33333_rot90.pdf'
ex_file3_rot180 = base_dir + 'filled/filled_33333_rot180.pdf'

Dots per inch used

In [ ]:
dpi = 300

## Coordinates comparison of the checkboxes

In [ ]:
def get_coords_json(json_data):
    coords = np.zeros((json_data['num_boxes'],2))
    count_ex = 0
    count_box = 0
    for i in range(json_data['num_boxes']):
        if count_box == json_data['exercises'][count_ex]['checkboxes'].__len__():
            count_ex = count_ex + 1
            count_box = 0
        coords[i] = json_data['exercises'][count_ex]['checkboxes'][count_box]['cords'][0:2]
        count_box = count_box + 1
    return coords

In [ ]:
with open(st_json_file1) as json_file:
    pypdf_coords = get_coords_json(json.load(json_file))
pypdf_coords

array([[105.961, 383.659],
       [105.961, 367.719],
       [105.961, 324.103],
       [105.961, 308.163],
       [105.961, 265.739],
       [105.961, 249.799],
       [105.961, 207.375],
       [105.961, 191.434],
       [105.961, 148.459],
       [105.961, 132.518],
       [105.961,  90.094],
       [105.961,  74.154],
       [105.961, 713.121],
       [105.961, 697.181],
       [105.961, 681.241],
       [105.961, 665.301],
       [105.961, 622.323],
       [105.961, 606.383],
       [105.961, 590.443],
       [105.961, 574.502],
       [105.961, 531.303],
       [105.961, 515.363],
       [105.961, 499.423],
       [105.961, 483.483],
       [105.961, 439.646],
       [105.961, 423.706],
       [105.961, 407.765],
       [105.961, 391.825],
       [105.961, 347.989],
       [105.961, 332.048],
       [105.961, 316.108],
       [105.961, 272.271],
       [105.961, 256.331],
       [105.961, 240.391],
       [105.961, 224.451],
       [105.961, 181.252],
       [105.961, 165.311],
 

In [ ]:
with open(filled_json_file3) as json_file:
    opencv_base_coords = get_coords_json(json.load(json_file))
opencv_base_coords

array([[ 517., 2474.],
       [ 517., 2563.],
       [ 517., 2805.],
       [ 517., 2893.],
       [ 517., 3129.],
       [ 517., 3218.],
       [ 517., 3453.],
       [ 517., 3542.],
       [ 517., 3781.],
       [ 517., 3869.],
       [ 517., 4105.],
       [ 517., 4194.],
       [ 517.,  644.],
       [ 517.,  732.],
       [ 517.,  821.],
       [ 517.,  909.],
       [ 517., 1148.],
       [ 517., 1237.],
       [ 517., 1325.],
       [ 517., 1414.],
       [ 517., 1654.],
       [ 517., 1742.],
       [ 517., 1831.],
       [ 517., 1919.],
       [ 517., 2163.],
       [ 517., 2252.],
       [ 517., 2340.],
       [ 517., 2429.],
       [ 517., 2672.],
       [ 517., 2761.],
       [ 517., 2849.],
       [ 517., 3093.],
       [ 517., 3181.],
       [ 517., 3270.],
       [ 517., 3359.],
       [ 517., 3599.],
       [ 517., 3687.],
       [ 517., 3776.],
       [ 517., 3864.],
       [ 517.,  644.],
       [ 517.,  732.],
       [ 517.,  821.],
       [ 517.,  909.],
       [ 51

In [ ]:
qrs1 = find_qrs_v1(st_file1)

In [ ]:
a = [[105.961,383.659,517.000,2474.000],
     [105.961,367.719,517.000,2563.000],
     [105.961,324.103,517.000,2805.000],
     [105.961,308.163,517.000,2893.000],
     [105.961,265.739,517.000,3129.000],
     [105.961,249.799,517.000,3218.000],
     [105.961,207.375,517.000,3453.000],
     [105.961,191.434,517.000,3542.000],
     [105.961,148.459,517.000,3781.000],
     [105.961,132.518,517.000,3869.000]]
np.array(a)

array([[ 105.961,  383.659,  517.   , 2474.   ],
       [ 105.961,  367.719,  517.   , 2563.   ],
       [ 105.961,  324.103,  517.   , 2805.   ],
       [ 105.961,  308.163,  517.   , 2893.   ],
       [ 105.961,  265.739,  517.   , 3129.   ],
       [ 105.961,  249.799,  517.   , 3218.   ],
       [ 105.961,  207.375,  517.   , 3453.   ],
       [ 105.961,  191.434,  517.   , 3542.   ],
       [ 105.961,  148.459,  517.   , 3781.   ],
       [ 105.961,  132.518,  517.   , 3869.   ]])

In [ ]:
print("| box | x - pyPDF | y - pyPDF | x - OpenCV | y - OpenCV |")
print("| --- | --- | --- | --- | --- |")
for i, row in enumerate(np.array(a)):
    print("|  %i | %.2f | %.2f | %.2f | %.2f |" % (i+1, row[0], row[1], row[2], row[3]))

| box | x - pyPDF | y - pyPDF | x - OpenCV | y - OpenCV |
| --- | --- | --- | --- | --- |
|  1 | 105.96 | 383.66 | 383.66 | 517.00 |
|  2 | 105.96 | 367.72 | 367.72 | 517.00 |
|  3 | 105.96 | 324.10 | 324.10 | 517.00 |
|  4 | 105.96 | 308.16 | 308.16 | 517.00 |
|  5 | 105.96 | 265.74 | 265.74 | 517.00 |
|  6 | 105.96 | 249.80 | 249.80 | 517.00 |
|  7 | 105.96 | 207.38 | 207.38 | 517.00 |
|  8 | 105.96 | 191.43 | 191.43 | 517.00 |
|  9 | 105.96 | 148.46 | 148.46 | 517.00 |
|  10 | 105.96 | 132.52 | 132.52 | 517.00 |


In [ ]:
trans_ppdf_opencv = get_trans(pypdf_coords, opencv_base_coords)
print(np.array([trans_ppdf_opencv[0][0], trans_ppdf_opencv[0][1], trans_ppdf_opencv[1], trans_ppdf_opencv[2]]))
print(np.array([trans_ppdf_opencv[0][0], trans_ppdf_opencv[0][1], trans_ppdf_opencv[1], trans_ppdf_opencv[2]])/400)

[1105.52613529 4604.98183947  180.            5.55417687]
[ 2.76381534 11.5124546   0.45        0.01388544]
