In [22]:
import numpy as np
import scipy as sc
import scipy.optimize

In [34]:
C1 = np.array([
    [0,1],
    [1,1],
    [1,0],
    [0,0]
])
C2_xtra = np.array([
    [0.5,1.2],
    [1.5,1.2],
    [1.5,0.2],
    [0.5,0.2]
])
def rot(alpha):
    '''clockwise rotation
    
    :param: alpha in 360 degrees
    '''
    alpha_rad = alpha*np.pi/180
    return np.array([
        [np.cos(alpha_rad), np.sin(alpha_rad)],
        [-np.sin(alpha_rad), np.cos(alpha_rad)]
    ])
C3_rot = C1@rot(90)


In [35]:
C3_rot

array([[-1.000000e+00,  6.123234e-17],
       [-1.000000e+00,  1.000000e+00],
       [ 6.123234e-17,  1.000000e+00],
       [ 0.000000e+00,  0.000000e+00]])

In [36]:
np.array([[0.5,0.2]]) +1*C1@rot(0)  - C2_xtra

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [37]:
np.array([[0.49,0.21]]) +.99*C1@rot(0.01)  - C2_xtra

array([[-1.01727876e-02, -1.50785622e-08],
       [-2.01728027e-02,  1.72772517e-04],
       [-2.00000151e-02,  1.01727876e-02],
       [-1.00000000e-02,  1.00000000e-02]])

In [38]:
(np.array([[0.49,0]]) +0.99*C1  - C2_xtra)**2

array([[0.0001, 0.0441],
       [0.0004, 0.0441],
       [0.0004, 0.04  ],
       [0.0001, 0.04  ]])

In [39]:
((np.array([[0.49,0]]) +0.99*C1  - C2_xtra)**2).sum()

0.1692

In [40]:
def trans(C1, C2):
    def sq(xs):
        x0, y0, scale, angle = xs
        C1_trans = np.array([[x0,y0]]) + scale*C1@rot(angle)
        return ((C1_trans - C2)**2).sum()
    x0_guess, y0_guess = C2[0,:] - C1[0,:]
    sol = sc.optimize.minimize(sq, (x0_guess, y0_guess, 1, 0), tol=1e-9, method='Powell')
    if not sol['success']:
        raise RuntimeError('Numerical error: could not find transformation matrix')
    return tuple(sol['x'])

In [41]:
trans(C1, C2_xtra)

(0.5, 0.19999999999999996, 1.0, 0.0)

In [42]:
trans(C1, C2_xtra + 1e-3*np.random.random((4,2)))

(0.5005634236490347,
 0.2002928460707557,
 1.000384837419675,
 0.020987542196671313)

In [43]:
trans(C1, C3_rot)

(-1.6510742998587072e-12,
 -1.1517537212075568e-12,
 0.9999999999975262,
 89.99999999986672)

In [44]:
trans(C1, C3_rot + 1e-3*np.random.random((4,2)))

(0.000255505195049494,
 0.0004205054805855773,
 0.9996934223721534,
 89.98839069331599)